---
- name: Добавить GPG ключ Elasticsearch
  rpm_key:
    state: present
    key: https://packages.elastic.co/GPG-KEY-elasticsearch

- name: Добавить репозиторий Elastic для YUM
  yum_repository:
    name: elastic-8.x
    description: Elastic repository for 8.x packages
    baseurl: https://artifacts.elastic.co/packages/8.x/yum
    gpgcheck: yes
    gpgkey: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    enabled: yes

- name: Установить Elastic APM Server
  yum:
    name: apm-server
    state: present

- name: Копировать конфигурацию APM Server
  template:
    src: apm-server.yml.j2
    dest: /etc/apm-server/apm-server.yml
    mode: '0644'
  notify: restart apm-server

- name: Запуск и автозапуск APM Server
  service:
    name: apm-server
    state: started
    enabled: yes
