---
- name: Add GPG key Elasticsearch
  rpm_key:
    state: present
    key: "{{ elastic_gpg_key_url }}"

- name: Add Repo Elastic for YUM
  yum_repository:
    name: "{{ elastic_repo_name }}"
    description: "{{ elastic_repo_description }}"
    baseurl: "{{ elastic_repo_baseurl }}"
    gpgcheck: yes
    gpgkey: "{{ elastic_gpg_key_url }}"
    enabled: yes

- name: Install Elastic APM Server
  yum:
    name: "{{ apm_server_package_name }}"
    state: present

- name: Copy config APM Server
  template:
    src: "{{ apm_server_config_template }}"
    dest: "{{ apm_server_config_dest }}"
    mode: '0644'
  notify: restart apm-server

- name: Enable and start APM Server
  service:
    name: "{{ apm_server_package_name }}"
    state: started
    enabled: yes
