- name: Download and install Elastic public signing key
  rpm_key:
    state: present
    url: https://artifacts.elastic.co/GPG-KEY-elasticsearch

- name: Add Elastic repository
  yum_repository:
    name: elastic-7.x
    description: Elastic repository for 7.x packages
    baseurl: https://artifacts.elastic.co/packages/7.x/yum
    gpgcheck: yes
    enabled: yes

- name: Install Filebeat
  yum:
    name: filebeat
    state: present

- name: Enable and start Filebeat service
  systemd:
    name: filebeat
    enabled: yes
    state: started

- name: Copy Filebeat configuration
  template:
    src: filebeat.conf.j2
    dest: /etc/filebeat/filebeat.yml
  notify: reload filebeat


