- name: Download and install Elastic public signing key
  command: rpm --import {{ elastic_gpg_key_url }}

- name: Add Elastic repository
  yum_repository:
    name: "{{ elastic_repo_name }}"
    description: "{{ elastic_repo_description }}"
    baseurl: "{{ elastic_repo_baseurl }}"
    gpgcheck: yes
    enabled: yes

- name: Install Filebeat
  yum:
    name: "{{ filebeat_package_name }}"
    state: present

- name: Enable and start Filebeat service
  systemd:
    name: "{{ filebeat_package_name }}"
    enabled: yes
    state: started

- name: Copy Filebeat configuration
  template:
    src: "{{ filebeat_config_template }}"
    dest: "{{ filebeat_config_dest }}"
  notify: reload filebeat


