---
- name: Download node_exporter
  get_url:
    url: "{{ node_exporter_download_url }}"
    dest: "{{ node_exporter_tmp_archive }}"
    mode: '0755'

- name: Extract node_exporter
  unarchive:
    src: "{{ node_exporter_tmp_archive }}"
    dest: "/tmp"
    remote_src: yes

- name: Move node_exporter binary to /usr/local/bin
  copy:
    src: "/tmp/node_exporter-{{ node_exporter_version }}.linux-amd64/node_exporter"
    dest: "{{ node_exporter_bin_path }}"
    mode: '0755'
    remote_src: yes

- name: Ensure node_exporter user exists
  user:
    name: "{{ node_exporter_service_name }}"
    shell: "/bin/false"
    createhome: no

- name: Create node_exporter systemd service file
  copy:
    content: |
      [Unit]
      Description=Node Exporter
      Wants=network-online.target
      After=network-online.target

      [Service]
      User=node_exporter
      Group=node_exporter
      Type=simple
      ExecStart=/usr/local/bin/node_exporter

      [Install]
      WantedBy=multi-user.target
    dest: "{{ node_exporter_service_file }}"
    mode: '0644'

- name: Enable and start node_exporter service
  systemd:
    name: "{{ node_exporter_service_name }}"
    enabled: yes
    state: started
