---
- name: Download node_exporter
  get_url:
    url: "https://github.com/prometheus/node_exporter/releases/download/v1.1.2/node_exporter-1.1.2.linux-amd64.tar.gz"
    dest: "/tmp/node_exporter.tar.gz"
    mode: '0755'

- name: Extract node_exporter
  unarchive:
    src: "/tmp/node_exporter.tar.gz"
    dest: "/tmp"
    remote_src: yes

- name: Move node_exporter binary to /usr/local/bin
  copy:
    src: "/tmp/node_exporter-1.1.2.linux-amd64/node_exporter"
    dest: "/usr/local/bin/node_exporter"
    mode: '0755'

- name: Ensure node_exporter user exists
  user:
    name: node_exporter
    shell: "/bin/false"
    createhome: no

- name: Create node_exporter systemd service file
  copy:
    content: |
      [Unit]
      Description=Node Exporter
      Wants=network-online.target
      After=network-online.target

      [Service]
      User=node_exporter
      Group=node_exporter
      Type=simple
      ExecStart=/usr/local/bin/node_exporter

      [Install]
      WantedBy=multi-user.target
    dest: "/etc/systemd/system/node_exporter.service"
    mode: '0644'

- name: Enable and start node_exporter service
  systemd:
    name: node_exporter
    enabled: yes
    state: started
