- name: Install Java
  yum:
    name: "{{ java_package_name }}"
    state: "{{ java_package_state }}"

- name: Download Gradle
  get_url:
    url: "{{ gradle_download_url }}"
    dest: /tmp/gradle-{{ gradle_version }}-bin.zip

- name: Mkdir {{ gradle_install_dir }}
  file:
    path: {{ gradle_install_dir }}
    state: directory

- name: unpack Gradle
  unarchive:
    src: /tmp/gradle-{{ gradle_version }}-bin.zip
    dest: {{ gradle_install_dir }}
    remote_src: yes

- name: Add Gradle in PATH
  lineinfile:
    path: /etc/profile.d/gradle.sh
    create: yes
    line: 'export PATH=$PATH:{{ gradle_path }}'

- name: Copy Java app on remote server
  synchronize:
    src: "{{ java_app_src }}"
    dest: "{{ java_app_dest }}"
    recursive: yes

- name: chmod Java app
  file:
    path: "{{ java_app_dest }}"
    state: directory
    owner: "{{ java_app_group }}"
    group: "{{ java_app_group }}"
    mode: "{{ java_app_mode }}"
    recurse: yes

- name: Build java with Gradle
  command: ./gradlew build -x test
  args:
    chdir: "{{ java_app_dest }}"

- name: Run java app
  shell: "nohup java -jar "{{ java_app_dest }}"/build/libs/spring-petclinic-3.1.0.jar > /dev/null 2>&1 &"
