---
- name: Install Amazon Corretto
  package:
    name: java-17-amazon-corretto-devel
    state: present

- name: Install Docker
  yum:
    name: docker
    state: present

- name: Docker run
  service:
    name: docker
    state: started
    enabled: yes

- name: Install gradle
  get_url:
    url: https://services.gradle.org/distributions/gradle-6.8.3-bin.zip
    dest: /tmp/gradle-6.8.3-bin.zip

- name: Unpack Gradle in /opt
  unarchive:
    src: /tmp/gradle-6.8.3-bin.zip
    dest: /opt/
    remote_src: yes

- name: Add gradle in PATH
  lineinfile:
    path: /etc/prodile.d/gradle.sh
    create: yes
    line: 'export PATH=$PATH:/opt/gradle-6.8.3/bin'
    mode: '0755'

- name: Source config
  shell: source /etc/profile.d/gradle.sh

- name: Build with gradle
  shell: 
    cmd: ./gradlew build
    chdir: 

- name: Run java app
  shell:
    cmd: java -jar build/libs/
    chdir: 
