---
- name: Add Grafana YUM repository
  yum_repository:
    name: "{{ grafana_repo_name }}"
    description: "{{ grafana_repo_description }}"
    baseurl: "{{ grafana_repo_baseurl }}"
    gpgcheck: "{{ grafana_repo_gpgcheck }}"
    enabled: yes
    gpgkey: "{{ grafana_repo_gpgkey }}"

- name: Install Grafana
  yum:
    name: "{{ grafana_package_name }}"
    state: "{{ grafana_package_state }}"

- name: Enable and start Grafana service
  systemd:
    name: grafana-server
    enabled: yes
    state: started
