---
- name: Add Grafana YUM repository
  yum_repository:
    name: grafana
    description: Grafana YUM repository
    baseurl: https://packages.grafana.com/oss/rpm
    gpgcheck: yes
    enabled: yes
    gpgkey: https://packages.grafana.com/gpg.key

- name: Install Grafana
  yum:
    name: grafana
    state: latest

- name: Enable and start Grafana service
  systemd:
    name: grafana-server
    enabled: yes
    state: started
