---
- name: Download and install the public signing key
  rpm_key:
    state: present
    key: "{{ elastic_gpg_key_url }}"

- name: Add Elasticsearch repository
  yum_repository:
    name: elasticsearch
    description: Elasticsearch repository for 7.x packages
    baseurl: "{{ elastic_repo_baseurl }}"
    gpgcheck: yes
    gpgkey: "{{ elastic_gpg_key_url }}"
    enabled: yes

- name: Install Elasticsearch
  yum:
    name: "{{ elastic_package_name }}"
    state: latest

- name: Enable Elasticsearch service
  systemd:
    name: "{{ elastic_package_name }}"
    enabled: yes
    state: started
