---
- name: Add user for Prometheus
  user:
    name: prometheus
    shell: /sbin/nologin
    system: true

- name: Create directories required by Prometheus
  file:
    path: "{{ item }}"
    state: directory
    owner: prometheus
    group: prometheus
    mode: '0755'
  loop:
    - /etc/prometheus
    - /var/lib/prometheus

- name: Download Prometheus
  get_url:
    url: "https://github.com/prometheus/prometheus/releases/download/v2.45.0/prometheus-2.45.0.linux-amd64.tar.gz"
    dest: "/tmp/prometheus-2.45.0.linux-amd64.tar.gz"
    checksum: "sha256:1c7f489a3cc919c1ed0df2ae673a280309dc4a3eaa6ee3411e7d1f4bdec4d4c5"

- name: Extract Prometheus package
  unarchive:
    src: "/tmp/prometheus-2.45.0.linux-amd64.tar.gz"
    dest: "/tmp"
    remote_src: true

- name: Move Prometheus binaries and directories
  command:
    cmd: rsync -a /tmp/prometheus-2.45.0.linux-amd64/{{ item }} /etc/prometheus/
  with_items:
    - prometheus
    - promtool
    - consoles
    - console_libraries

- name: Copy Prometheus config file
  template:
    src: prometheus.yml.j2
    dest: /etc/prometheus/prometheus.yml
    owner: prometheus
    group: prometheus
    mode: '0644'

- name: Create systemd service file for Prometheus
  become: yes
  copy:
    dest: /etc/systemd/system/prometheus.service
    content: |
      [Unit]
      Description=Prometheus Service
      After=network.target

      [Service]
      User=prometheus
      Group=prometheus
      Type=simple
      ExecStart=/usr/local/bin/prometheus \
        --config.file /etc/prometheus/prometheus.yml \
        --storage.tsdb.path /var/lib/prometheus/ \
        --web.console.templates=/etc/prometheus/consoles \
        --web.console.libraries=/etc/prometheus/console_libraries

      [Install]
      WantedBy=multi-user.target
  notify:
    - name: Reload systemd
    - name: Enable Prometheus service
    - name: Start Prometheus service

- name: Ensure Prometheus is enabled and started
  become: yes
  systemd:
    name: prometheus
    state: started
    enabled: true

