---
- name: Install Nginx
  package:
    name: "{{ nginx_package_name }}"
    state: present

- name: Start Nginx
  service:
    name: "{{ nginx_service_name }}"
    state: started
    enabled: yes

- name: Copy Nginx configuration file
  template:
    src: "{{ nginx_conf_template }}"
    dest: "{{ nginx_conf_dest }}"
  notify: 
    - reload nginx
...

