---
- hosts: mon01
  become: yes
  roles:
    - elasticsearch
    - kibana
    - logstash

- hosts: prom01
  become: yes
  roles:
    - prometheus

- hosts: app01
  become: yes
  roles:
    - docker
    - nginx
    - java  
