---
- hosts: mon01
  become: yes
  roles:
    - elasticsearch
    - kibana
    - logstash
    - node_exporter
    - grafana

- hosts: prom01
  become: yes
  roles:
    - prometheus
    - node_exporter

- hosts: app01
  become: yes
  roles:
    - docker
    - nginx
    - java
    - filebeat
    - node_exporter

- hosts: apm01
  become: yes
  roles:
    - apm_server
