---
- name: Add Kibana repository
  yum_repository:
    name: kibana
    description: Kibana repository for 7.x packages
    baseurl: https://artifacts.elastic.co/packages/7.x/yum
    gpgcheck: yes
    gpgkey: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    enabled: yes

- name: Install Kibana
  yum:
    name: kibana
    state: latest

