java_package_name: java-17-amazon-corretto
java_package_state: present

gradle_version: 7.2
gradle_download_url: https://services.gradle.org/distributions/gradle-{{ gradle_version }}-bin.zip
gradle_install_dir: /opt/gradle
gradle_path: "{{ gradle_install_dir }}/gradle-{{ gradle_version }}/bin"

java_app_src: /Users/maksimyarhunin/monitoring_education/java-spring-pets
java_app_dest: /home/ec2-user/java-spring-pets
java_app_owner: ec2-user
java_app_group: ec2-user
java_app_mode: '0755'
